TestWebApp/Controllers/LabourerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using TestWebApp.Models;
using TestWebApp.Models.ProductPackage;
using TestWebApp.Pages;

namespace TestWebApp.Controllers
{
    public class LabourerController : Controller
    {
        string connectionString = "server=84.246.4.143;port=9139;Database=koster3mollshop;Uid=Koster3molladmin;Pwd=pi9!rtd@;SslMode=none;";

        public IActionResult Index()
        {
            //Return alle Labourers in een List
            //Deze shit gebruiken we niet meer en is nutteloos nu
            return View("/Index");
        }

        [HttpGet]
        public IActionResult Write()
        {
            return View();
        }

        //Note, je kan dit nu alleen callen met als actie = DetailsById
        [ActionName("DetailsById")]
        public IActionResult Details(string labourerId)
        {

            tbl_labourerdata labourer = MollShopContext.FindLabourerById(labourerId);
            return View("Details", labourer);

        }

        [ActionName("DetailsByModel")]
        public IActionResult Details(OfferedLabourerService package)
        {
            tbl_labourerdata labourer = new tbl_labourerdata();
            labourer.fld_address = package.fld_address;
            labourer.fld_dateofbirth = package.fld_dateofbirth.ToString();
            labourer.fld_email = package.fld_email;
            labourer.fld_firstname = package.fld_email;
            labourer.fld_gender = package.fld_gender;
            labourer.fld_labourerid = package.fld_labourerid;
            labourer.fld_lastname = package.fld_lastname;
            labourer.fld_phonenumber = package.fld_phonenumber;
            labourer.fld_zipcode = package.fld_zipcode;

            return View("Details", labourer);
        }
    }
}

TestWebApp/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PayPalPayment.PayPal;
using TestWebApp.Models;
using TestWebApp.Models.ProductPackage;
using TestWebApp.ElasticSearch.Queries;
using TestWebApp.Models.Orders;
using TestWebApp.ElasticSearch;

namespace TestWebApp.Controllers
{
    public class ShoppingCartController : Controller
    {
        public IActionResult ShoppingCart()
        {
            List<OfferedLabourerService> serviceList = new List<OfferedLabourerService>();

            //Check if we're logged in. 
            bool loggedIn = SessionController.returnLoggedIn(this.HttpContext);

            if (!loggedIn)
            {
                //Not logged in, get products from cookies
                List<string> keyList = Request.Cookies.Keys.Where(k => k.StartsWith("SC")).ToList();
                serviceList = Utility.CookieController.fetchItemsInCookies(keyList);
            }

            else
            {
                //Logged in, get products from database
                List<Object> offeredServiceIds = MollShopContext.GetShoppingCartItems((int)HttpContext.Session.GetInt32("UserId"));
                serviceList = new List<OfferedLabourerService>();

                foreach (Object id in offeredServiceIds)
                {
                    serviceList.Add(ElasticSearch.Queries.EsOLSQuery<object>.findByOfferedServiceId((int)id));
                }
            }


            PayPalConfig payPalConfig = PayPalService.getPayPalConfig();
            ViewBag.payPayConfig = payPalConfig;

            return View(serviceList);
        }




        //This Action is called from the initial shopping cart page
        //The user will click this when they are ready to purchase their products
        //It will return 1 of 2 views, depending on the users' login status
        public IActionResult PaymentAuthentication(string orders)
        {
            //First check if there are any orders. If not, nothing should happen. Refresh the page
            if (orders == null)
            {
                return RedirectToAction("ShoppingCart", "ShoppingCart");
            }

            //Retrieve the user status to check whether the user is logged in or not
            UserStatusModel userStatus = SessionController.CheckLoggedInStatus(this.HttpContext);

            //Put the orders in the browser session. This refreshes the list, so if the user has altered their shopping cart, it'll always be up to date when entering the ordering sequence
            SessionController.refreshOrderList(orders, this.HttpContext);





            if (userStatus.LoggedIn)
            {
                //User is logged in already, so return the PaymentMethod view
                List<OfferedLabourerService> olsList = ParseOrdersToOLS();

                tbl_userdata user = MollShopContext.FindUserById((int)this.HttpContext.Session.GetInt32("UserId"));
                Tuple<List<OfferedLabourerService>, tbl_userdata> tuple = Tuple.Create(olsList, user);

                return View("OrderSpecification", tuple);
            }

            else
            {
                //User is not logged in. return the PaymentAuthentication view
                return View();
            }
        }

        //This action does the authentication for registered users that are about to make a purchase
        public IActionResult DoAuthentication(string fld_emailaddress, string fld_password)
        {
            LoginModel loginMdl = new LoginModel(fld_emailaddress, fld_password);
            loginMdl = DatabaseController.Login(loginMdl, this.HttpContext);



            ViewBag.Message = loginMdl.Message;

            if (loginMdl.UserId <= 0)
            {
                return View("PaymentAuthentication", this.HttpContext.Session.GetString("ORD"));
            }
            else
            {
                this.HttpContext.Session.SetString("OrderMail", loginMdl.EmailAddress);

                tbl_userdata user = MollShopContext.FindUserById(loginMdl.UserId);
                return RedirectToAction("OrderSpecification", user);
            }
        }

        //This action gets called when the user decides to not use an account when making their purchase
        public IActionResult UnregisteredAuthentication(string fld_emailaddress)
        {
            this.HttpContext.Session.SetString("OrderMail", fld_emailaddress);

            tbl_userdata user = new tbl_userdata();
            user.fld_email = fld_emailaddress;
            return RedirectToAction("Orderspecification", user);
        }

        public IActionResult OrderSpecification(tbl_userdata user)
        {
            //This view will show the order the user is about to make
            //They can make last minute changes: for example: a different mailing address, a target send date, etc
            //By clicking the proceed button, the user will be directed to the PaymentMethod view

            //List all the services

            List<OfferedLabourerService> olsList = ParseOrdersToOLS();

            Tuple<List<OfferedLabourerService>, tbl_userdata> tuple = Tuple.Create(olsList, user);
            return View(tuple);
        }

        public IActionResult PaymentMethod(string fld_email, string fld_firstname, string fld_lastname, string fld_address, string fld_zipcode)
        {
            //The variables received from this form will be used to create the confirmation email later on
            HttpContext.Session.SetString("FORM", fld_firstname + ";" + fld_lastname + ";" + fld_address + ";" + fld_zipcode + ";" + fld_email);


            //This view will show the users their options for paying
            //In reality, the user would be able to choose between IDEAL, PayPal, etc. However, we only have PayPal

            List<OfferedLabourerService> olsList = ParseOrdersToOLS();

            PayPalConfig payPalConfig = PayPalService.getPayPalConfig();
            ViewBag.payPayConfig = payPalConfig;


            return View(olsList);
        }

        public IActionResult CreateOrders(string fld_email)
        {
            try
            {
                //Create the orders

                List<int> orderIds = ParseOrdersToList();
                Order order = new Order();

                order.fld_email = fld_email;
                if (fld_email == null)
                {
                    //The OrderMail Session Key is null. This means the user is already logged in, and did not need to save that key
                    order.fld_email = HttpContext.Session.GetString("User");
                }

                //Insert the Orders in the database
                foreach (int orderId in orderIds)
                {
                    order.fld_OfferedServiceId = orderId;
                    MollShopContext.CreateRow(order, "tbl_orders");

                    //If the user is logged in, we need to remove the orders from their database shopping cart
                    if (fld_email == null)
                    {
                        DatabaseController.RemoveFromShoppingCart(orderId, (int)HttpContext.Session.GetInt32("UserId"));
                    }
                }

                //With this, we have created the orders, and the user is now in the process of paying for their products. We can delete the orders.

                //First, we move the orders in the Session to a new Key. This way, we can still summarize the Orders if the order was successful later, but at the same time
                //We prevent the orders from being made multiple times over by user accident

                //Put the Ordered items in "PUR", for "Purchased
                this.HttpContext.Session.SetString("PUR", this.HttpContext.Session.GetString("ORD"));

                //Remove the orders from the Session
                this.HttpContext.Session.Remove("ORD");

                //Remove the ShoppingCart items from the Cookies
                List<string> items = HttpContext.Request.Cookies.Keys.Where(s => s.StartsWith("SC")).ToList();

                foreach (string item in items)
                {
                    Response.Cookies.Delete(item);
                }

            }

            catch (Exception e)
            {

            }

            return View("Success");
        }

        public async Task<IActionResult> Success()
        {
            //This action returns the result of the payment.
            //This is when the order will receive it's first update: it's either payed or encountered an error.
            var result = PDTHolder.Success(Request.Query["tx"].ToString());

            //Update the order status and history, update the offeredservice


            //Get previously entered order information
            string form = HttpContext.Session.GetString("FORM");
            char separator = ';';
            string[] formVars = form.Split(separator);

            //Send a confirmation email
            await ConstructOrderVerificationMailAsync(formVars);


            string email = formVars[4];
            List<int> offeredServiceIds = ParsePursToList();

            foreach(int olsId in offeredServiceIds)
            {

                //Fetch the order id
                int orderId = MollShopContext.FindOrderId(olsId, email);
                
                
                //Insert a new order history
                tbl_orderhistory history = new tbl_orderhistory();
                history.fld_ActionDate = DateTime.Now;
                history.fld_lastAction = "Paid order";
                history.fld_orderstatus = "Sent";
                history.fld_orderid = orderId;

                MollShopContext.CreateRow(history, "tbl_orderhistory");

                //Insert a new order status
                tbl_orderstatus orderStatus = new tbl_orderstatus();

TestWebApp/Views/ShoppingCart/Checkout.cshtml
@model TestWebApp.Models.UserStatusModel
@{
    Layout = "/Pages/Shared/_Layout.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html>
<head>
    <title>MOLL | Register</title>
</head>

<body>
    <div id="menu_underheader">
        <h1>Register | Please fill in your details below</h1>
    </div>

    <div>

        <p>No account? Fill in your email address</p>
        <form asp-action="ProceedToPayment" asp-controller="ShoppingCart">
            <label>Email address</label>
            <input name="fld_emailaddress" type="text" />


            <button type="submit">Proceed to payment</button>
        </form>
        <!-- Geef de optie om in te loggen of om als unregistered user alleen een email adres op te geven-->
        <p>Are you and existing user? Log in! WTF</p>
        <form asp-action="ProceedToPayment" asp-controller="ShoppingCart">
            <label>Email Address</label>
            <input name="fld_emailaddress" type="text" />
            <label>Password</label>
            <input name="fld_password" type="password" />
        </form>
    </div>
    </html>
</body>

TestWebApp/Views/ShoppingCart/OrderConfirmMail.cshtml
@using TestWebApp.Models.ProductPackage;
@using TestWebApp.Models;

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@model Tuple<List<OfferedLabourerService>, string[]>

    <body style='box-sizing: border-box;font-family: Lato, Lucida Grande, Lucida Sans Unicode, Tahoma, Sans-Serif; width: auto;height: 100vw;margin: 0 0 0 0;'>
        <div id='section_form' style='box-sizing: border-box;background: #f4f4f4;padding-top: 2vw;padding-bottom: 5vw;'>
            <img id='circlelogo' src='https://i.imgur.com/lrkjNdQ.png' style='box-sizing: border-box;width: 8vw;height: auto;margin: auto;display: block;position: relative;top: 20px;z-index: 999;'>
            <div id='rectangle' style='box-sizing: border-box;;width: 40vw;height: auto;background: white;padding: 30px;margin: auto;border-radius: 30px;z-index: 950;'>

                <div class='registrationform' style='box-sizing: border-box;'>
                    <table style='box-sizing: border-box;border: 0px solid #ffac35;margin: auto;text-align: center;font-size: 16px;margin-top: 20px;'>
                        <tbody style='box-sizing: border-box;'>
                            <tr style='box-sizing: border-box;'>
                                <td style='box-sizing: border-box;'>
                                    <p style='box-sizing: border-box;color: #666666;font-size: 27px;font-weight: 700;font-family: Lato, Lucida Grande, Lucida Sans Unicode, Tahoma, Sans-Serif;margin-bottom: 5%;'>Thank you for your purchase!</p>
                                    <p>With kind regards, </p>
                                </td>
                            </tr>
                            <tr>
                                <p>Dear @Model.Item2[0] @Model.Item2[1],
                                <p>

                                <p>Your order has been successfully processed. Thank you for choosing MOLL Webshop.
                                <p>
                                <p>All information about your orders are available in your account. A confirmation mail has also been sent to your chosen labourers, who will be ready to start working for you on the target date!
                                <p>

                                    <br />
                                    <hr />
                                <p style="font-size: 13px; text-align: center"> Your Order: </p>

                                <div style="padding: 5px; background-color:#dbdbdb; height:40px; width:90%; margin:auto; font-size: 9px">

                                    <div style="padding: 3px; background-color: #dbdbdb; font-weight: bold; width: 18%; float:left; ">
                                    </div>
                                    <div style="padding: 3px; background-color: #dbdbdb; font-weight: bold; width: 30%; float:left;">
                                        <p>Description</p>
                                    </div>
                                    <div style="padding: 3px; background-color: #dbdbdb; font-weight: bold; width: 10%; float:left;">
                                        <p> Order Id </p>
                                    </div>
                                    <div style="padding: 3px; background-color: #dbdbdb; font-weight: bold; width: 20%; float:left;">
                                        <p>Target Delivery date</p>
                                    </div>
                                    <div style="padding: 3px; background-color: #dbdbdb; font-weight: bold; width: 3%; float:left;">
                                        <p>Price</p>
                                    </div>

                                </div>

                                @{
						foreach(OfferedLabourerService pack in Model.Item1)
						{

                                    <div style="padding: 5px; overflow: auto; width:90%; margin:auto;">

                                        <div style="padding: 3px; font-size: 9px; width: 18%; float:left;">
                                            <img style="max-width:100px; float:left; margin: 5px;" src="@pack.fld_imagelink" />

                                        </div>
                                        <div style="padding: 5px; font-size: 9px; width: 30%; float:left;">
                                            <p>@pack.fld_name offered by @pack.fld_firstname @pack.fld_lastname</p>
                                            <p>@pack.fld_description</p>
                                        </div>
                                        <div style="padding: 3px; font-size: 9px; width: 10%; float:left;">
                                            <p>@pack.fld_offeredserviceid</p>
                                        </div>
                                        <div style="padding: 3px; font-size: 9px;  width: 20%; float:left;">
                                            <p> @DateTime.Now.AddDays(7)</p>
                                        </div>
                                        <div style="padding: 3px; font-size: 9px;  width: 3%; float:left;">
                                            <p>€@pack.fld_cost</p>
                                        </div>

                                    </div>

                            }
                                }


                                <div style="padding: 5px; height:50px; width:90%; margin:auto; background-color: #dbdbdb;">

                                    <div style="padding: 3px; font-size: 9px; width: 18%; float:left;">
                                    </div>
                                    <div style="padding: 3px; font-size: 9px; width: 30%; float:left;">

                                    </div>
                                    <div style="padding: 3px; font-size: 9px; width: 10%; float:left;">
                                    </div>
                                    <div style="padding: 3px; font-size: 12px;  width: 20%; float:left; background-color: #dbdbdb;">
                                        <p>Total: </p>
                                    </div>
                                    <div style="padding: 3px; font-size: 12px;  width: 3%; float:left; background-color: #dbdbdb;">
                                        <p>€@Model.Item1.Sum(s => s.fld_cost) </p>
                                    </div>

                                </div>

                                <p style="text-align: center; font-size: 13px">Order paid using: Paypal</p>

                                <div style="padding: 5px; margin: auto; width: 90%; background-color: #dbdbdb; height: 100px;">

                                    <div style="background-color: #dbdbdb; padding: 5px; font-size: 11px; text-align: center; width: 30%; float:left;">

                                    </div>

                                    <div style="background-color: #dbdbdb; padding: 5px; font-size: 11px; text-align: center; width: 30%; float:left;">
                                        <p style="font-weight: bold;">Working location </p>
                                        <p> Address: @Model.Item2[2]</p>
                                        <p> Zipcode: @Model.Item2[3]</p>
                                    </div>

                                    <div style="background-color: #dbdbdb; padding: 5px; font-size: 11px; text-align: center; width: 30%; float:left;">

                                    </div>
                                </div>
                            </tr>

                            <tr style='box-sizing: border-box;'>
                                <td style='box-sizing: border-box;'>
                                    <a href=\"https://localhost:44346"><button style='box-sizing: border-box;background-color: #ffac35;color: white;padding: 10px 10px;border: none;cursor: pointer;opacity: 0.9;width: 220px;height: 100px;font-size: 25px;font-weight: 700;border-radius: 7px;-moz-transition: all 0.2s ease 0s;-o-transition: all 0.2s ease 0s;transition: all 0.2s ease 0s;margin: 0 auto;text-align: center;'>MOLL WebShop</button> </a>

                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </body>

TestWebApp/Views/ShoppingCart/ShoppingCart.cshtml
@model List<TestWebApp.Models.ProductPackage.OfferedLabourerService>
@using TestWebApp.Models;
@{
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<head>
    <style>
        .gridDiv {
            display: grid;
            grid-template-columns: max-content 30% auto auto auto auto;
            padding: 10px;
            background: #f4f4f4 ;
        }

        .gridHeader {
            padding: 5px;
            font-size: 11px;
            background-color: #dbdbdb;
            font-weight: bold;
        }

        .gridElement {
            padding: 5px;
            font-size: 12px;
            position: relative;
        }

            .gridElement img {
                border: 1px solid black;
                max-height: 80px;
                margin: 5px;
            }

            .gridElement .verticalCenter {
                position: absolute;
                top: 30%;
            }

        #clickableElement:hover {
            transition: background-color 1s ease;
            background-color: #dbdbdb;
            cursor: pointer;
        }

        .gridSummary {
            padding: 5px;
            font-size: 13px;
            font-weight: bold;
            background-color: #dbdbdb;
        }
    </style>
</head>

<body bgcolor="#f4f4f4">
    <section class="section-content bg padding-y-sm">
        <div class="container">
            @if (Model.Count > 0)
            {


                <div id="menu_underheader">
                    <h1>Shopping Cart</h1>
                </div>
                <div class="gridDiv">
                    <div class="gridHeader">
                    </div>
                    <div class="gridHeader">
                        <p>Description</p>
                    </div>
                    <div class="gridHeader">
                        <p> Offered by </p>
                    </div>
                    <div class="gridHeader">
                        <p>Working hours</p>
                    </div>
                    <div class="gridHeader">
                        <p>Price</p>
                    </div>
                    <div>
                    </div>

                    @foreach (var item in Model)
                    {



                        <div class="gridElement">
                            <img style=" float: left;" src="@item.fld_imagelink" onclick="location.href='@Url.Action("Details", "Service", new { offeredserviceid = @item.fld_offeredserviceid })'" />
                        </div>

                        <div class="gridElement" id="clickableElement" onclick="location.href='@Url.Action("Details", "Service", new { offeredserviceid = @item.fld_offeredserviceid })'">

                            <p style="font-weight: bold">@item.fld_name</p>
                            <p>@item.fld_description</p>
                        </div>



                        <div class="gridElement" id="clickableElement" onclick="location.href='@Url.Action("DetailsById", "Labourer", new { labourerid = item.fld_labourerid })'">
                            @{
                                string img = "post-user-avatar.png";
                                if (item.fld_gender == "Female")
                                {
                                    img = "post-user-avatar-female.png";
                                }
                            }
                            <img style=" float:left;" src="~/images/@img" />
                            <div class="labourerTekst">
                                <p style="font-weight: bold">@item.fld_firstname @item.fld_lastname</p>
                                <p>@item.fld_address <br /> @item.fld_zipcode</p>
                                <p></p>

                                <p>@item.fld_email</p>
                            </div>
                        </div>

                        <div class="gridElement">

                            <div class="verticalCenter">
                                @item.fld_timefirst - @item.fld_timelast
                            </div>
                        </div>

                        <div class="gridElement">
                            <div class="verticalCenter">
                                €@item.fld_cost
                            </div>
                        </div>

                        <div class="gridElement">

                            <button style="top: 30%;  position: absolute;" onclick="location.href='@Url.Action("RemoveFromShoppingcart", "Cookie", new { fld_offeredserviceid = @item.fld_offeredserviceid })'"> remove </button>
                        </div>

                    }




                    <div class="gridSummary">
                    </div>
                    <div class="gridSummary">
                    </div>
                    <div class="gridSummary">
                    </div>
                    <div class="gridSummary">
                        <p>Articles: </p>
                        <p>Total: </p>
                    </div>
                    <div class="gridSummary">
                        <p> @Model.Count</p>
                        <p> €@Model.Sum(s => s.fld_cost) </p>
                    </div>



                </div>
            }

            @{
                if (Model.Count < 1)
                {
                    <p>Your Shopping cart is empty.<a href="@Url.Action("Index", "Service")">Find your service!</a> </p>
                }
            }
            </div>
        </section>


            <!--Eind:  De shopping cart items die worden gerendered-->
            <!--Begin: De popup die tevoorschijn komt als de user op de Plus Button klikt--
            <div class="modal fade" tabindex="-1" id="AddAService"
                 data-keyboard="false" data-backdrop="static">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">
                                ×
                            </button>
                            <h4 class="modal-title">Hey hallo daar</h4>
                        </div>
                        <div class="modal-body">
                            <div style="outline: red solid 2px" id="SearchResult">
                                <div id="searchResult">
                                    <p>hey</p>
                                </div>
                            </div>
                            <div style="outline: solid green 2px">
                                @{Html.RenderPartial("SearchForm", new OLSSearchModel());}
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" id="btnHideModal" class="btn btn-primary button button4">
                                Hide
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <!--Eind: De popup die tevoorschijn komt als de user op de Plus Button klikt-->
            <button id="checkOutBtn" style="margin: auto; display:block;" type="button" onclick="location.href='@Url.Action("PaymentAuthentication", "ShoppingCart", new { orders = Model.Select(f => f.fld_offeredserviceid).Aggregate("", (current, next) => current + " " + next) })'">Check out</button>
            <script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script>


            </script>
</body>

TestWebApp/Views/ShoppingCart/Success.cshtml
@{
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<head>
    <title>MOLL | Login</title>
</head>

<body bgcolor="#f4f4f4">
    <div id="menu_underheader">
        <h1>Payment page</h1>
    </div>
    <div id="section_form">
        <img id="circlelogo" src="~/images/img_loginLogo.png" />
        <div id="rectangle">
            <div class="labourerdetails">
                <table>
                    <tbody>
                        <tr>
                            <td>Your payment was a succes !</td>

                            @ViewData["test"];
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>